version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
