comment: off

coverage:
  precision: 2
  round: down
  range: "95...100"

  status:
    project:
      default:
        target: 90%
        threshold: 5%
    patch: yes
    changes: no

ignore:
  - "api"
