ARG OPENSEARCH_VERSION
FROM opensearchproject/opensearch:${OPENSEARCH_VERSION}

ARG opensearch_path=/usr/share/opensearch
ARG opensearch_yml=$opensearch_path/config/opensearch.yml

ARG SECURE_INTEGRATION
RUN if [ "$SECURE_INTEGRATION" != "true" ] ; then \
    $opensearch_path/bin/opensearch-plugin remove opensearch-anomaly-detection || true; \
    $opensearch_path/bin/opensearch-plugin remove opensearch-skills || true; \
    $opensearch_path/bin/opensearch-plugin remove opensearch-ml || true; \
    $opensearch_path/bin/opensearch-plugin remove opensearch-security; \
    fi
