name: Publish Docs to Github Pages
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    name: Update gh-pages with docs
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18.x
      - name: Install Tools
        run: |
          sudo apt install -y jq
          npm install -g jsdoc
      - name: Generate Docs
        run: |
          export PACKAGE_VERSION=$(jq .version package.json -r | awk -F. '{print $1"."$2}')
          export DOC_FOLDER=docs/$PACKAGE_VERSION 
          jsdoc api lib -d $DOC_FOLDER -r --readme README.md
          cp *.md $DOC_FOLDER
          cp *.txt $DOC_FOLDER
          cp OpenSearch.svg $DOC_FOLDER
      - name: Deploy Docs to gh-pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
          enable_jekyll: true
