name: Integration
# trigger on every commit push and PR for all branches
on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ['**']
    paths-ignore:
      - '**/*.md'

env:
  OPENSEARCH_VERSION: latest

jobs:
  helpers-integration-test:
    name: Helpers integration test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      SECURE_INTEGRATION: false

    steps:
      - uses: actions/checkout@v4

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs OpenSearch cluster
        run: |
          make cluster.clean cluster.opensearch.build cluster.opensearch.start

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # NPM started understanding yarn.lock file starting from v7
      - name: Update NPM
        shell: bash
        run: |
          export NPM_VERSION=$(npm -v)
          export IS_NPM_SUITABLE=$(node -p "parseInt(process.env.NPM_ROOT, 10) >= 7")
          if [ "$IS_NPM_SUITABLE" == "false" ]; then
            echo "NPM needs upgrading!"
            npm i npm@7 -g
          fi

      - name: Install
        run: |
          npm install

      - name: Integration test
        run: |
          npm run test:integration:helpers

  helpers-secure-integration-test:
    name: Helpers integration test with secure cluster
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      SECURE_INTEGRATION: true

    steps:
      - uses: actions/checkout@v4

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs OpenSearch secure cluster
        run: |
          make cluster.clean cluster.opensearch.build cluster.opensearch.start

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # NPM started understanding yarn.lock file starting from v7
      - name: Update NPM
        shell: bash
        run: |
          export NPM_VERSION=$(npm -v)
          export IS_NPM_SUITABLE=$(node -p "parseInt(process.env.NPM_ROOT, 10) >= 7")
          if [ "$IS_NPM_SUITABLE" == "false" ]; then
            echo "NPM needs upgrading!"
            npm i npm@7 -g
          fi

      - name: Install
        run: |
          npm install

      - name: Integration test with secure cluster
        run: |
          npm run test:integration:helpers-secure
